quiz_data = [
    {"question": "Python was created by Guido van Rossum.", "answer": "True"},
    {"question": "The Earth has two moons.", "answer": "False"},
    {"question": "HTML is a programming language.", "answer": "False"},
    {"question": "The capital of Japan is Tokyo.", "answer": "True"},
    {"question": "A kilogram is heavier than a gram.", "answer": "True"},
    {"question": "Sharks are mammals.", "answer": "False"},
    {"question": "The Sun revolves around the Earth.", "answer": "False"},
    {"question": "Water boils at 100 degrees Celsius at sea level.", "answer": "True"},
    {"question": "An octagon has eight sides.", "answer": "True"},
    {"question": "Light travels slower than sound.", "answer": "False"},
    {"question": "The human body has 206 bones.", "answer": "True"},
    {"question": "The Great Wall of China is visible from space with the naked eye.", "answer": "False"},
    {"question": "Mount Everest is the tallest mountain on Earth.", "answer": "True"},
    {"question": "Venus is the closest planet to the Sun.", "answer": "False"},
    {"question": "C is an object-oriented programming language.", "answer": "False"},
    {"question": "The chemical symbol for Gold is Au.", "answer": "True"},
    {"question": "Bats are blind.", "answer": "False"},
    {"question": "The Pacific Ocean is the largest ocean on Earth.", "answer": "True"},
    {"question": "The square root of 64 is 8.", "answer": "True"},
    {"question": "Penguins can fly naturally.", "answer": "False"},
    {"question": "The speed of light is faster than the speed of sound.", "answer": "True"},
    {"question": "A leap year has 366 days.", "answer": "True"},
    {"question": "The currency of India is the Rupee.", "answer": "True"},
    {"question": "Spiders have six legs.", "answer": "False"},
    {"question": "The CPU is known as the brain of the computer.", "answer": "True"}
]